### PR TITLE
Renamed custom.py to common.py

### PR DESCRIPTION
**Pull request by DanDevDan**
Renamed the custom.py to common.py.

### CODE REVIEW

**Review by ItsDrike — CHANGES_REQUESTED** [review]
This only removes **`cogs/custom.py`** it doesn't actually rename it.

**Comment by SignalDevX** [comment]
It removes cogs/custom.py and replaces with cogs/common.py, with classes changed as well.

**Comment by ItsDrike** [comment]
> It removes cogs/custom.py and replaces with cogs/common.py, with classes changed as well.

You probably forgot to stage it when committing because in **files changed** tab there is only the removal of **`cogs/custom.py`** and adjustment to **`main.py`**, but there are no changes or renaming to it.

image

**Comment by SignalDevX** [comment]
You're right. Must of missed it.

**Pull request closed without merging**
