### PR TITLE
added documentation command

### PR DESCRIPTION
**Pull request by Anubhav1603**
this command has Rapptz fuzzy finder and able to search documentation like R.danny

### CODE REVIEW

**Comment by Anubhav1603** [comment]
i tried to make changes in code but if i remove if part or else part its error out

**Comment by therealdaneel** [comment]
You need to check your changes against flake8 and resolve those conflicts because this 
image
is why your code is failing azure pipelines

**Review by ActuallyDaneel — CHANGES_REQUESTED** [review]
Looks like you copy/pasted a command from somewhere, in order to make it merge-ready, you'll have to make a few changes

- add `documentation.py` to the extension list in `__main__.py`
- resolve flake8 errors/warnings
- add docstrings to all the functions and classes
- add typehints to all function arguments

**Review by ItsDrike — CHANGES_REQUESTED** [review]
As was already pointed out, resolve all `flake8` issues found by Azure Pipelines and read [`CONTRIBUTING.py`](https://github.com/The-Codin-Hole/HotWired-Bot/blob/master/CONTRIBUTING.md) which contains the formatting rules for our codebase, please make sure to follow them in your code.

Also, note that we don't accept copied code from other bots, so things like `"Credits to github.com/Rapptz"` are unacceptable, you'll need to write your own non-copied functions as we require original non-copied codebase (If there is something copied, it was done with authors permission not to mention them and it's usually just some smaller parts of code), please respect that.

**Comment by Anubhav1603** [comment]
can i share my code which i use ItsDrike for other commands

**Comment by therealdaneel** [comment]
> can i share my code which i use ItsDrike for other commands

if it's your own original code, then you can use it. ItsDrike's issue was that you were copy/pasting code you didn't have permission to use.

**Pull request closed without merging**
