### PR TITLE
Add Prefixes that can be changed on a server basis

### PR DESCRIPTION
**Pull request by janaSunrise**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This is not a proper way of doing this, we should wait for a database

**Review by ActuallyDaneel — CHANGES_REQUESTED** [review]
A prefix length limit should be implemented to prevent someone from cluttering the json with a 2000 char prefix (i'm thinking 15-20 characters max)

**Comment by ItsDrike** [comment]
> This is not a proper way of doing this, we should wait for a database

@e-xe 
We will need to implement this as another API request which will save it into its internal database, that way we can extract or change this prefix easily from the web pannel as it can also make API requests.
Implementing a full database for the bot isn't necessary due to the presence of API

**Comment by ItsDrike** [comment]
> A prefix length limit should be implemented to prevent someone from cluttering the json with a 2000 char prefix (i'm thinking 15-20 characters max)

Even though we won't be using `json` to store these in the future I still agree, we should define a maximum length for the prefix.

**Pull request merged**
