### PR TITLE
Added Job Finding Abilties to bot

### PR DESCRIPTION
**Pull request by GrandMoff100**
command `job-find [amount]` web scrapes the discord job website for jobs at discord. Where `[amount]` has a default of three.

### CODE REVIEW

**Review by janaSunrise — COMMENTED** [review]
#93 must be merged first as this branch is branched off from nsfw branch :100:

**Comment by therealdaneel** [comment]
you haven't added any "job" abilities to the Bot. The changes made focus exclusively on nsfw, for which there already is a PR [here](https://github.com/The-Codin-Hole/HotWired-Bot/pull/93)

**Comment by GrandMoff100** [comment]
If you look at disjobs.py in bot/cogs there is a cog that utilizes DiscordJobFinder class from bot/utils/jobfinder.py in GrandMoff100/HotWired-Bot to scrape the discord jobs website for jobs available there. So please reconsider your review.

**Comment by GrandMoff100** [comment]
But I’m confused as to why my job finding commits don’t show up here.

**Pull request closed without merging**
